- name: create ec2 and r53 instance
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05f323a81d59459e1
    zone_id: "Z00484781U0O1QG6VX0D8"
    domain_name: "mitha.fun" 
    instances:
    - mongodb
    
  tasks:
  - name: creating ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: print public ip_address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].public_ip_address}}"
    loop: "{{ec2_output.results}}"

  - name: print private ip_address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address}}"
    loop: "{{ec2_output.results}}"