- name : creating ec2 instance
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05f323a81d59459e1
    zone_id: Z00484781U0O1QG6VX0D8
    domain_name: mitha.fun
    instances:
    - mongodb

  tasks:
  - name: ec2_instance_mongo
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
      name: "{{item}}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
     

 # - name: printing the ec2_output
 #   ansible.builtin.debug:
 #     msg: "{{ec2_output}}"

 # - name : print public ip                                  
 #   ansible.builtin.debug:
 #    msg: "{{ item.instance[0].public_ip_address }}"
 #   loop: "{{ec2_output.results}}"

 # - name : print private ip
 #   ansible.builtin.debug:
 #     msg: "{{ item.instance[0].private_ip_address }}"
 #   loop: "{{ec2_output.results}}"

- name: creatiing rote53 records
  amazon.aws.route53:
    state: present
    zone: "{{ domain_name }}"
    record: "{{ item.item }}. {{ domain_name}}"
    type: A
    ttl: 1
    value: "{{ item.instance[0].private_ip_address }}"
    wait: true
    overwrite: true
  loop: "{{ ec2_output.results }}"