- name: installing mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: configuring mongodb
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongo db
    ansible.builtin.package:
      name: mongodb-org
      state: present

   -name: Replace old version string
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Ensure nginx service is started and enabled
    ansible.builtin.service:
      name: mongodb
      state: started
      enabled: yes

 